### ISSUE TITLE
 Creating a duplicate database object for the same connection

### ISSUE THREAD

**Issue by maximbashevoy** [siddharth23/cypress-postgres#2]
After repeatedly running a test with a call to `cy.task("dbQuery"...` I get warnings:

```
WARNING: Creating a duplicate database object for the same connection.
    at module.exports (e2e-tests/node_modules/cypress-postgres/cypress/plugins/index.js:21:14)
    at dbQuery (/e2e-tests/cypress/plugins/index.js:24:29)
    at invoke (/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:41:14)
```

Is it to do with the way dbQuery task is added in plugins? Any advice?

**Comment by dhalawa-bread** [comment]
I'm facing the same . Is there anyway to fix it ?

**Comment by kawadesoni** [comment]
const db = pgp(connection);
  let response = db.any(query);
  pgp.end();
  return response;
Above changes needs to be added to the index.js
After reading DB, close the connection before returning.

**Comment by KleisKlasKluss** [comment]
I'm facing the same issue too.

In my `plugins/index.js` file I have

```javascript
const postgres = require('cypress-postgres');

module.exports = (on, config) => {
    on('task', {
        dbQuery: query => postgres(query.query, query.connection),
    });
}
```


When I run tests using the task `dbQuery` I get this in terminal:
```
WARNING: Creating a duplicate database object for the same connection.
    at module.exports (/Users/<username>/<path>/node_modules/cypress-postgres/cypress/plugins/index.js:21:14)
    at dbQuery (/Users/klango/<username>/<path>/tests/cypress/plugins/index.js:39:27)
    at invoke (/Users/<username>/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:47:14)
```

**Comment by nurbashanghai** [comment]
> I'm facing the same issue too.
> 
> In my `plugins/index.js` file I have
> 
> ```js
> const postgres = require('cypress-postgres');
> 
> module.exports = (on, config) => {
>     on('task', {
>         dbQuery: query => postgres(query.query, query.connection),
>     });
> }
> ```
> 
> When I run tests using the task `dbQuery` I get this in terminal:
> 
> ```
> WARNING: Creating a duplicate database object for the same connection.
>     at module.exports (/Users/<username>/<path>/node_modules/cypress-postgres/cypress/plugins/index.js:21:14)
>     at dbQuery (/Users/<username>/<path>/tests/cypress/plugins/index.js:39:27)
>     at invoke (/Users/<username>/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:47:14)
> ```

hey man! did u manage to solve it? Im facing this issue right now

**Comment by KleisKlasKluss** [comment]
> > I'm facing the same issue too.
> > In my `plugins/index.js` file I have
> > ```js
> > const postgres = require('cypress-postgres');
> > 
> > module.exports = (on, config) => {
> >     on('task', {
> >         dbQuery: query => postgres(query.query, query.connection),
> >     });
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I run tests using the task `dbQuery` I get this in terminal:
> > ```
> > WARNING: Creating a duplicate database object for the same connection.
> >     at module.exports (/Users/<username>/<path>/node_modules/cypress-postgres/cypress/plugins/index.js:21:14)
> >     at dbQuery (/Users/<username>/<path>/tests/cypress/plugins/index.js:39:27)
> >     at invoke (/Users/<username>/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:47:14)
> > ```
> 
> hey man! did u manage to solve it? Im facing this issue right now

Sorry, I didn't manage to fix it... Please let me know if you find a working solution 😄

**Comment by kawadesoni** [comment]
Yes i did.. have forked ur proj and raised a PR too

**Comment by nurbashanghai** [comment]
> > > I'm facing the same issue too.
> > > In my `plugins/index.js` file I have
> > > ```js
> > > const postgres = require('cypress-postgres');
> > > 
> > > module.exports = (on, config) => {
> > >     on('task', {
> > >         dbQuery: query => postgres(query.query, query.connection),
> > >     });
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > When I run tests using the task `dbQuery` I get this in terminal:
> > > ```
> > > WARNING: Creating a duplicate database object for the same connection.
> > >     at module.exports (/Users/<username>/<path>/node_modules/cypress-postgres/cypress/plugins/index.js:21:14)
> > >     at dbQuery (/Users/<username>/<path>/tests/cypress/plugins/index.js:39:27)
> > >     at invoke (/Users/<username>/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:47:14)
> > > ```
> > 
> > 
> > hey man! did u manage to solve it? Im facing this issue right now
> 
> Sorry, I didn't manage to fix it... Please let me know if you find a working solution 😄

 ```
const pgp = require('pg-promise')();
 const postgressConfig = require(require('path').resolve('cypress.json'));
 
function dbConnection (query,userDefineConnection)  {
   let connection = postgressConfig.db
   if (userDefineConnection!=undefined){
     connection=userDefineConnection
   }
   const db = pgp(connection);
   return db.any(query).finally(db.$pool.end)
 }

// import cppg from 'cypress-postgres';
  module.exports = on => {
    on("task", {
        dbQuery:(query)=> dbConnection(query.query,query.connection)
    });

};
```
I tried this one, and it works perfect. No warning or errors

**Comment by KleisKlasKluss** [comment]
Thanks @nurbashanghai  - worked like a charm! 🚀 🥳
